### ISSUE TITLE
Not working on 2.1.45alpha3

### ISSUE THREAD

**Issue by AnKingMed** [giovannihenriksen/Anki-Simulator#58]
Just if you want to get a head start on updating things

Caught exception:
Traceback (most recent call last):
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/__init__.py", line 54, in <lambda>
    action.triggered.connect(lambda _, did=deck_id: open_simulator_dialog(did))
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/__init__.py", line 46, in open_simulator_dialog
    dialog = SimulatorDialog(
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/gui/dialogs.py", line 100, in __init__
    self.deckChooser.setDeckName(deck_name)
AttributeError: 'DeckChooser' object has no attribute 'setDeckName'

**Comment by giovannihenriksen** [comment]
Thanks for reporting this. This has been fixed by @RumovZ and will be pushed to AnkiWeb soon.
