### PR TITLE
Fix setting DeckChooser deck in 2.1.45

### LINKED ISSUE #58: Not working on 2.1.45alpha3
Just if you want to get a head start on updating things

Caught exception:
Traceback (most recent call last):
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/__init__.py", line 54, in <lambda>
    action.triggered.connect(lambda _, did=deck_id: open_simulator_dialog(did))
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/__init__.py", line 46, in open_simulator_dialog
    dialog = SimulatorDialog(
  File "/Users/Nick/Library/Application Support/Anki2/addons21/817108664/gui/dialogs.py", line 100, in __init__
    self.deckChooser.setDeckName(deck_name)
AttributeError: 'DeckChooser' object has no attribute 'setDeckName'

### PR DESCRIPTION
**Pull request by RumovZ**
This will require a separate branch for Anki 2.1.45+ on AnkiWeb, of course. Closes #58.

### CODE REVIEW

**Comment by fernandovmacedo** [comment]
I've built the addon using the source from the commit and it doesn't load on 2.1.45

**Comment by giovannihenriksen** [comment]
Thanks for the fix! I added compatibility for versions below 2.1.45 and updated the changelog.
